create database grocery;
use grocery;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date date,
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

SELECT * FROM customers LIMIT 10;
SELECT * FROM orders LIMIT 10;
SELECT * FROM order_details LIMIT 10;

-- Customers with unique orders --
select count(distinct cust_id) as customers from orders;

-- Which customers have placed highest orders --
select c.cust_id,c.cust_name,count(o.ord_id) as order_count from customers c
join orders o on c.cust_id = o.cust_id
group by c.cust_id,c.cust_name
order by order_count desc;

-- What the average and total purchase value per customer --
select c.cust_id,c.cust_name,sum(od.total_price) as Total_Spent,avg(od.total_price) as avg_spent from customers c
join orders o on c.cust_id = o.cust_id
join order_details od on o.ord_id = od.ord_id
group by c.cust_id,c.cust_name;

-- Who are the top 5 Customers based on total purchase --
select c.cust_id,c.cust_name,sum(od.total_price) as Total_Spent from customers c
join orders o on c.cust_id = o.cust_id
join order_details od on o.ord_id = od.ord_id
group by c.cust_id,c.cust_name
order by Total_Spent desc limit 5;

-- How many Products exist in each category --
select c.cat_id,c.cat_name, count(*) as Total_Products from categories c
join products p on c.cat_id = p.cat_id
group by c.cat_id,c.cat_name;

-- Average Price by Category --
select c.cat_id,c.cat_name, avg(price) as Avg_Product_Price from categories c
join products p on c.cat_id = p.cat_id
group by c.cat_id,c.cat_name;

-- Which products have the highest total sales volume (by quantity) --
select p.prod_id,p.prod_name, sum(od.quantity) as total_quantity from products p
join order_details od on p.prod_id = od.prod_id
group by p.prod_id,p.prod_name
order by total_quantity desc;

-- What is the total revenue generated by each product --
select p.prod_id,p.prod_name, sum(od.total_price) as prod_revenue from products p
join order_details od on p.prod_id = od.prod_id
group by p.prod_id,p.prod_name;

-- How do product sales vary by category and supplier --
select c.cat_name,
s.sup_name,
sum(od.total_price) as revenue from categories c 
join products p on c.cat_id = p.cat_id
join order_details od on p.prod_id = od.prod_id
join supplier s on p.sup_id = s.sup_id
group by c.cat_name,s.sup_name;

-- How many orders have been placed in total --
select count(*) as total_orders from orders;

-- What is the average value per order --
select avg(order_total) as avg_order_value
from (
select ord_id,sum(total_price) as order_total from
order_details
group by ord_id) t;

-- On which dates were the most orders placed --
select order_date,
count(*) as total_orders
from orders
group by order_date
order by total_orders desc;

-- What are the monthly trends in order volume and revenue --
select 
month(order_date) as month,
count(distinct o.ord_id) as total_orders,
sum(od.total_price) as revenue
from orders o 
join order_details od on o.ord_id = od.ord_id
group by month(order_date)
order by month;

-- How do order patterns vary across weekdays and weekends --
select 
if(dayofweek(order_date) in (1,7), "Weekend","Weekday") as day_type,
count(*) as total_orders
from orders
group by day_type;

-- How many suppliers are there in the database --
select count(*) as count_of_suppliers from supplier;

-- Which supplier provides the most products --
select s.sup_id,s.sup_name,count(*) as no_of_products
from supplier s 
join products p on s.sup_id = p.sup_id
group by s.sup_id,s.sup_name
order by no_of_products desc limit 1;

-- What is the average price of products from each supplier --
select s.sup_id,s.sup_name,
avg(p.price) as avg_product_price 
from supplier s
join products p on s.sup_id = p.sup_id
group by s.sup_id,s.sup_name;

-- Which suppliers contribute the most to total product sales (by revenue) --
select s.sup_id,s.sup_name,
sum(od.total_price) as revenue from
supplier s 
join products p on s.sup_id = p.sup_id
join order_details od on p.prod_id = od.prod_id
group by s.sup_id,s.sup_name
order by revenue desc; 

-- How many employees have processed orders --
select count(distinct emp_id) from orders;

-- Which employees have handled the most orders --
select e.emp_id,e.emp_name,
count(o.ord_id) as no_of_sales from employees e 
join orders o on e.emp_id = o.emp_id
group by e.emp_id,e.emp_name
order by no_of_sales desc;

-- What is the total sales value processed by each employee --
select e.emp_id,e.emp_name,
sum(od.total_price) as total_sales_value
from employees e 
join orders o on e.emp_id = o.emp_id
join order_details od on o.ord_id = od.ord_id
group by e.emp_id,e.emp_name;

-- What is the average order value handled per employee --
select e.emp_id,e.emp_name,
avg(order_total) as average_order_value
from (
select o.emp_id,o.ord_id, 
sum(od.total_price) as order_total
from orders o 
join order_details od on o.ord_id = od.ord_id
group by o.emp_id,o.ord_id
) t
join employees e on t.emp_id = e.emp_id
group by e.emp_id,e.emp_name;

-- What is the relationship between quantity ordered and total price --
select quantity,total_price from order_details; -- quantity and total price have direct proportional relationship --

-- What is the average quantity ordered per product --
select p.prod_id,p.prod_name,
avg(od.quantity) as avg_quantity 
from products p 
join order_details od on p.prod_id = od.prod_id
group by p.prod_id,p.prod_name;

-- How does the unit price vary across products and orders --
select p.prod_name,
max(od.each_price) as max_price,
min(od.each_price) as min_price,
avg(od.each_price) as avg_price
from products p 
join order_details od on p.prod_id = od.prod_id
group by p.prod_name; -- The each price does not vary because every product has a fixed price --
